### ISSUE TITLE
address encoding updates from Feb 2016 "editor mask" meetings

### ISSUE THREAD

**Issue by paregorios** [DCLP/dclpxsltbox#173]
There are a number of encoding changes envisioned as a result of discussions, which have been being discussed in email. This "epic" ticket will bind together the various subordinate issues (surfacing them from the email thread), some of which will no doubt drive XSLT and other changes, not just XML re-encoding or expansion.

Next steps:
- [ ] Create a separate issue for each "NEW" section in [59749_Example of new changes.xml](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml)
  - [x] name for display: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L7) ➡️  #206
  - [x] ancient archives/libraries in ```<collection>```: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L91) ➡️  this was resolved, after some changes in direction, with #21. Issue #25 had an effect on order of display in HTML.
  - [x] ```<material>``` in ```<supportDesc><support>```: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L99) ➡️  #207
  - [x] ```<dimensions>``` in ```<supportDesc><support>```: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L99) :arrow_right: Issue: #192 
  - [x] Information about writing style (```<handDesc>```): [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L113) ➡️  issue #208
  - [x] multiple parts of papyrus in ```<msParts>``` in header: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L203) ➡️  issue #322
  - [x] ```<biblScope>``` for a sequence of page ranges: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L1647) ➡️  issue #323
  - [x] Alternative Authors, Quoted Authors: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L1659)
  - [x] ```<bibl type="illustration">```: [example](https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d#file-59749_example_of_new_changes-xml-L1702)
- [x] Append discussion of provenance and the ancient archive from related email thread to the corresponding ticket
- [x] Tie together and normalize other tickets dealing with provenance, e.g., #6

**Comment by paregorios** [comment]
I've gisted the file mentioned above: https://gist.github.com/paregorios/be8e927d366129e1e0f605a5b6959e9d

**Comment by paregorios** [comment]
The open tasks above are for me to run down. I suspect they are all dealt with now in other tickets.
